### ISSUE TITLE
z/OS license concerns

### ISSUE THREAD

**Issue by coral** [tateru/tateru#5]
hello i am trying to acquire a z/OS license for my mainframe can this project assist with this?

**Comment by bluecmd** [comment]
Hello @coral! z/OS is not on the roadmap at this time, and to my knowledge the deployment models for z/OS are not compatible with Ansible - but if somebody wants to add it we encourage it!

As ArchLinux, which we use for the installer, was chosen for its multiple architecture support (and s390x is one of them) I see no reason why you couldn't use it for zLinux or similar however.

I will close this issue now, but it can be reopened if somebody wants to do this in the future.
